// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAeoUmkYWOjjmg__ByUG622DFixN6YJQo',
    appId: '1:327562841894:web:e5006ead18731694217be7',
    messagingSenderId: '327562841894',
    projectId: 'lista-e3dae',
    authDomain: 'lista-e3dae.firebaseapp.com',
    storageBucket: 'lista-e3dae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDMkxlikybZYNT2WdusCdYOqgJ1FZi2B4',
    appId: '1:327562841894:android:77ec68322823961f217be7',
    messagingSenderId: '327562841894',
    projectId: 'lista-e3dae',
    storageBucket: 'lista-e3dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALcXRkGuhj2UT26Q_t0DC_M8--TQlQJ5g',
    appId: '1:327562841894:ios:2dd59666beade388217be7',
    messagingSenderId: '327562841894',
    projectId: 'lista-e3dae',
    storageBucket: 'lista-e3dae.appspot.com',
    iosClientId:
        '327562841894-4u950fabkbf2vek631j028nqne7j1m1o.apps.googleusercontent.com',
    iosBundleId: 'com.marcinmiszewski.lista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALcXRkGuhj2UT26Q_t0DC_M8--TQlQJ5g',
    appId: '1:327562841894:ios:2dd59666beade388217be7',
    messagingSenderId: '327562841894',
    projectId: 'lista-e3dae',
    storageBucket: 'lista-e3dae.appspot.com',
    iosClientId:
        '327562841894-4u950fabkbf2vek631j028nqne7j1m1o.apps.googleusercontent.com',
    iosBundleId: 'com.marcinmiszewski.lista',
  );
}
